# Generated by Django 2.2.6 on 2019-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191125_2046'),
        ('accounts', '0002_auto_20191125_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genre_liker',
        ),
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(null=True, related_name='like_users', to='movies.Genre'),
        ),
    ]
