# Generated by Django 2.2.4 on 2019-11-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191121_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre_liker',
            field=models.ManyToManyField(null=True, related_name='liker_users', to='movies.Genre'),
        ),
    ]
