# Generated by Django 2.2.6 on 2019-11-25 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
