# Generated by Django 2.2.4 on 2019-11-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watchgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Grade'),
        ),
    ]
