# Generated by Django 2.2.6 on 2019-11-25 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_genre_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='watchgrade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movies',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='review_user',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_like',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_directors',
            field=models.ManyToManyField(related_name='director_movies', to='movies.Director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_genres',
            field=models.ManyToManyField(related_name='genre_movies', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
