# Generated by Django 2.2.4 on 2019-11-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(),
        ),
    ]
